# Generated by Django 2.2.1 on 2019-05-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_auto_20190511_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Published',
            new_name='published',
        ),
    ]
